name: Terraform CI/CD

on:
  push:
    branches:
      - pre-prod
      - prod
  pull_request:

jobs:
  terraform:
    name: 'Terraform Plan & Apply'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./envs/${{ github.ref_name }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init -backend-config="../../bootstrap/backend-${{ github.ref_name }}.tf"

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"

      # Optional: Auto apply only in pre-prod (NOT in prod)
      - name: Terraform Apply
        if: github.ref_name == 'pre-prod'
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
