name: Terraform CI/CD

on:
  push:
    branches:
      - pre-prod
      - prod
  pull_request:
    branches:
      - pre-prod
      - prod

jobs:
  terraform:
    name: 'Terraform Plan & Apply'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./envs/${{ github.head_ref || github.ref_name }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"

      - name: Terraform Apply (only on push to pre-prod)
        if: github.event_name == 'push' && github.ref_name == 'pre-prod'
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
